### ISSUE TITLE
Error in Developer Interface loadNextImage() 

### ISSUE THREAD

**Issue by tajmone** [tajmone/pmotion-assets#10]
@jan-cosmigo, There seems to be a mistake in the `loadNextImage()` function in the original _[Developer Interface]_ document, where the `delayMs` parameter is a variable in the Delphi function signature, but a pointer in the C++ function:

```delphi
function loadNextImage( colorFrame,
                        colorFramePalette,
                        alphaFrame,
                        alphaFramePalette: Pointer;
                        var delayMs: word
): boolean; stdcall;
```

```cpp
bool  __stdcall loadNextImage( unsigned char*  colorFrame,
                               unsigned char*  colorFramePalette,
                               unsigned char*  alphaFrame,
                               unsigned char*  alphaFramePalette,
                               unsigned short* delayMs
);
```
By looking at the C++ sources of the sample plugin from Cosmigo website, the correct one is the C++ function, where `delayMs` is a pointer (i.e. the plugin passes the value by writing its pointer).

- _[Developer Interface]_ — at Cosmigo website.
- _[Developer Interface][here]_ — in this repository website.

I can't fix it in the repository document unless it's fixed upstream, on the Cosmigo website, for the doc in this repo is meant to be a faithful copy of the original — i.e., unless it's OK with you (but then I should remove the statement regarding it being a faithful reproduction).

-------------------------------------------------------------------------------

- [ ] When original document is fixed on Cosmigo website, fix it also in this repository.

[Developer Interface]: https://www.cosmigo.com/pixel_animation_software/plugins/developer-interface
[here]: https://tajmone.github.io/pmotion-assets/Developer_Interface.html#_loadnextimage

**Comment by jan-cosmigo** [comment]
Both is correct. With Delphi Pascal the pointer turns into a "var" parameter which is "by reference" and has the same logic as giving a pointer or more similar using the &-operator.
