### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by tajmone** [tajmone/pmotion-assets#14]
@jan-cosmigo, please enable __Discussions__ from the repository settings, which will allow us to engage in general discussion on PMNG related topics without cluttering Issues (which should be restricted to tracking practical tasks for the repository development).

The Discussions feature wasn't available at the time the repository was created, and I forgot to enable it. Now I don't have access to the Settings panel, so I have to ask you to enable it.

Thanks.

**Comment by jan-cosmigo** [comment]
Done
