### ISSUE TITLE
Info on canExtractPalette()

### ISSUE THREAD

**Issue by tajmone** [tajmone/pmotion-assets#5]
_Missing info on DLL functions._

Is the `canExtractPalette()` a generic DLL function gathering info about the plug-in supported features (e.g. like `isReadSupported()`) or does it apply to the specific files being processed? In other words, is it a plug-in registration function or is called on a per-file basis?

For more info, see also:

- [Cosmigo Forum » _HELP: More File I/O Interface Clarifications_]
- tajmone/pmotion-purebasic#1

[Cosmigo Forum » _HELP: More File I/O Interface Clarifications_]: https://community.cosmigo.com/t/help-more-file-i-o-interface-clarifications/739

**Comment by jan-cosmigo** [comment]
It is called on plugin level. I updated the docs a bit:

_The application may support functions to load the color palette from a graphic file without loading the graphic/bitmap data. It uses this function to determine if the plugin can be used there as well. In that case the plugin is added in dialogs used when loading color palettes._

I also moved the function docs to the is...Supported() functions.
