### ISSUE TITLE
Must define unused DLL functions

### ISSUE THREAD

**Issue by tajmone** [tajmone/pmotion-assets#6]
_Missing info on DLL functions._

I need to understand if DLL functions specifically targeting import or export functionality can be left out entirely in those plug-ins that won't use them — i.e. if these functions still require defining `DLLProcedure`s that do nothing, or if they can simply be omitted since PM wouldn't try to call them after having acknowledged the plug-in supported features via the registration functions.

For example, an import plug-in shouldn’t expect any calls to `beginWrite()` or
`writeNextImage()`, and an export plug-in shouldn’t expect any calls to `getTransparentColor()` or `isAlphaEnabled()`.

For more info, see also:

- [Cosmigo Forum » _HELP: More File I/O Interface Clarifications_]
- tajmone/pmotion-purebasic#2

[Cosmigo Forum » _HELP: More File I/O Interface Clarifications_]: https://community.cosmigo.com/t/help-more-file-i-o-interface-clarifications/739

**Comment by jan-cosmigo** [comment]
Yes, the check functions should be optimized. At the moment these functions must be there. We could change this with V7.3 to and make them to be required conditionally.
