### ISSUE TITLE
Setting Error in getImageCount()

### ISSUE THREAD

**Issue by tajmone** [tajmone/pmotion-assets#8]
I need a clarification about the plugin function `getImageCount()`.

This function is documented as being able to return error, but it's the only function of those that can set error that is also expected to return a value (i.e. the number of frames).

I'm assuming that in case of error the function is also to return _false_ (0), and that it's not enough to just set the error. I'm assuming that, since at least 1 image is expected by PM, a return value of 0 would be considered an error.

If this is the case, it might be worth mentioning it in the interface documentation, because it's not obvious.

Se also:

- tajmone/pmotion-purebasic#5

**Comment by jan-cosmigo** [comment]
The doc is wrong there.
Actually I don't read the value with image plugins (but that's not important).
With animation plugins the value is taken as it is given, just like with width and height. Errors are not allowed. I fixed the doc at my site.
