### ISSUE TITLE
Error in Developer Interface writeNextImage()

### ISSUE THREAD

**Issue by tajmone** [tajmone/pmotion-assets#9]
@jan-cosmigo, There seems to be a mistake in the description of the `writeNextImage()` function in the original _[Developer Interface]_ document, which wrongly mentions the `width` and `height` parameters in the parameter table — which are not in the function signature, and shouldn't be there either.

- _[Developer Interface]_ — at Cosmigo website.
- _[Developer Interface][here]_ — in this repository website.

Probably these two parameters ended up in the table accidentally, due to copy and paste operations. 

I can't fix it in the repository document unless it's fixed upstream, on the Cosmigo website, for the doc in this repo is meant to be a faithful copy of the original — i.e., unless it's OK with you (but then I should remove the statement regarding it being a faithful reproduction).

-------------------------------------------------------------------------------

- [ ] When original document is fixed on Cosmigo website, fix it also in this repository.

[Developer Interface]: https://www.cosmigo.com/pixel_animation_software/plugins/developer-interface
[here]: https://tajmone.github.io/pmotion-assets/Developer_Interface.html#_writenextimage

**Comment by jan-cosmigo** [comment]
Yes, this is a mistake. Width and height are given with beginWrite(). I fixed this at my site.
